// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnpgnfjwqnraxyfykjks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRucGduZmp3cW5yYXh5ZnlramtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNDMyMTEsImV4cCI6MjA1ODYxOTIxMX0.IH2oWi6T8UKVv0kfY4eWJZU5rG42YqDYDP2pLwFTj_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);